import torch as th
from omnigibson.object_states import (
    ToggledOn,
    OnTop,
    Inside,
    Open,
    NextTo,
    Under,
    AttachedTo,
    Touching,
    OnFire,
    Covered,
    Contains,
    Filled,
    Cooked,
    Frozen,
)

ROBOT_OBJECT_DISTANCE_THRESHOLD = 0.5  # meters


def check_progress(env, check_specs):
    """Generic progress checker using declarative specs."""
    objs = env.task.object_scope
    results = {}

    for name, spec in check_specs.items():
        check_type = spec[0]

        if check_type == "near":
            # ("near", robot_key, obj_key) - robot should always be first
            robot, obj = objs[spec[1]].unwrapped, objs[spec[2]].unwrapped

            # Get all robot links to check: root_link and all eef_links
            robot_links_to_check = [robot.root_link] + list(robot.eef_links.values())

            # Get all object links
            obj_links = list(obj.links.values())

            # Check minimum distance between any robot link and any object link
            is_near = False
            for robot_link in robot_links_to_check:
                robot_pos = robot_link.get_position_orientation()[0]
                for obj_link in obj_links:
                    obj_pos = obj_link.get_position_orientation()[0]
                    # Only consider x and y coordinates (horizontal distance)
                    dist = th.linalg.norm(robot_pos[:2] - obj_pos[:2])
                    if dist < ROBOT_OBJECT_DISTANCE_THRESHOLD:
                        is_near = True
                        break
                if is_near:
                    break

            results[name] = is_near

        elif check_type == "state":
            # Check if it's a relational or non-relational state based on argument pattern
            if len(spec) == 4 and isinstance(spec[3], bool):
                # ("state", obj_key, state_name, expected_bool) - non-relational state, e.g. ToggledOn, Open
                obj = objs[spec[1]]
                results[name] = obj.exists and obj.unwrapped.states[spec[2]].get_value() == spec[3]
            elif len(spec) == 5:
                # ("state", obj1_key, state_name, obj2_key, expected_bool) - relational state with explicit bool, e.g. Inside, OnTop
                if spec[3] not in objs:
                    # Special case: e.g. category "tree.n.01" is not in object scope
                    all_instances = [
                        inst for inst, category in env.task.object_instance_to_category.items() if category == spec[3]
                    ]
                    assert len(all_instances) > 0, f"Could not find any instances for category {spec[3]}"
                    obj1 = objs[spec[1]]
                    results[name] = any(
                        obj1.exists
                        and objs[inst].exists
                        and obj1.unwrapped.states[spec[2]].get_value(objs[inst].unwrapped) == spec[4]
                        for inst in all_instances
                    )
                else:
                    obj1, obj2 = objs[spec[1]], objs[spec[3]]
                    results[name] = (
                        obj1.exists
                        and obj2.exists
                        and obj1.unwrapped.states[spec[2]].get_value(obj2.unwrapped) == spec[4]
                    )
            else:
                raise ValueError(f"Invalid state spec: {spec}")

        elif check_type == "exists":
            # ("exists", obj_key, expected_bool) - check if object exists
            if len(spec) == 3 and isinstance(spec[2], bool):
                results[name] = objs[spec[1]].exists == spec[2]
            else:
                raise ValueError(f"Invalid exists spec: {spec}")

    return results


# Task specifications
CHALLENGE_TASKS_PROGRESS_APPROXIMATION = {
    "turning_on_radio": lambda env: check_progress(
        env,
        {
            "robot_near_radio": ("near", "agent.n.01_1", "radio_receiver.n.01_1"),
            "radio_picked_up": ("state", "radio_receiver.n.01_1", OnTop, "table.n.02_1", False),
            "radio_on": ("state", "radio_receiver.n.01_1", ToggledOn, True),
        },
    ),
    "picking_up_trash": lambda env: check_progress(
        env,
        {
            "robot_near_trash_can": ("near", "agent.n.01_1", "ashcan.n.01_1"),
            "robot_near_can_of_soda_1": ("near", "agent.n.01_1", "can__of__soda.n.01_1"),
            "robot_near_can_of_soda_2": ("near", "agent.n.01_1", "can__of__soda.n.01_2"),
            "robot_near_can_of_soda_3": ("near", "agent.n.01_1", "can__of__soda.n.01_3"),
            "can_of_soda_1_picked_up": ("state", "can__of__soda.n.01_1", OnTop, "floor.n.01_1", False),
            "can_of_soda_2_picked_up": ("state", "can__of__soda.n.01_2", OnTop, "floor.n.01_1", False),
            "can_of_soda_3_picked_up": ("state", "can__of__soda.n.01_3", OnTop, "floor.n.01_1", False),
            "can_of_soda_1_not_on_floor_2": ("state", "can__of__soda.n.01_1", OnTop, "floor.n.01_2", False),
            "can_of_soda_2_not_on_floor_2": ("state", "can__of__soda.n.01_2", OnTop, "floor.n.01_2", False),
            "can_of_soda_3_not_on_floor_2": ("state", "can__of__soda.n.01_3", OnTop, "floor.n.01_2", False),
            "can_of_soda_1_in_trash": ("state", "can__of__soda.n.01_1", Inside, "ashcan.n.01_1", True),
            "can_of_soda_2_in_trash": ("state", "can__of__soda.n.01_2", Inside, "ashcan.n.01_1", True),
            "can_of_soda_3_in_trash": ("state", "can__of__soda.n.01_3", Inside, "ashcan.n.01_1", True),
        },
    ),
    "putting_away_Halloween_decorations": lambda env: check_progress(
        env,
        {
            "cabinet_open": ("state", "cabinet.n.01_1", Open, True),
            "robot_near_candle_1": ("near", "agent.n.01_1", "candle.n.01_1"),
            "robot_near_candle_2": ("near", "agent.n.01_1", "candle.n.01_2"),
            "robot_near_candle_3": ("near", "agent.n.01_1", "candle.n.01_3"),
            "candle_1_picked_up": ("state", "candle.n.01_1", OnTop, "floor.n.01_1", False),
            "candle_2_picked_up": ("state", "candle.n.01_2", OnTop, "floor.n.01_1", False),
            "candle_3_picked_up": ("state", "candle.n.01_3", OnTop, "floor.n.01_1", False),
            "candle_1_in_cabinet": ("state", "candle.n.01_1", Inside, "cabinet.n.01_1", True),
            "candle_2_in_cabinet": ("state", "candle.n.01_2", Inside, "cabinet.n.01_1", True),
            "candle_3_in_cabinet": ("state", "candle.n.01_3", Inside, "cabinet.n.01_1", True),
            "robot_near_pumpkin_1": ("near", "agent.n.01_1", "pumpkin.n.02_1"),
            "robot_near_pumpkin_2": ("near", "agent.n.01_1", "pumpkin.n.02_2"),
            "pumpkin_1_picked_up": ("state", "pumpkin.n.02_1", OnTop, "floor.n.01_1", False),
            "pumpkin_2_picked_up": ("state", "pumpkin.n.02_2", OnTop, "floor.n.01_1", False),
            "pumpkin_1_in_cabinet": ("state", "pumpkin.n.02_1", Inside, "cabinet.n.01_1", True),
            "pumpkin_2_in_cabinet": ("state", "pumpkin.n.02_2", Inside, "cabinet.n.01_1", True),
            "robot_near_caldron": ("near", "agent.n.01_1", "caldron.n.01_1"),
            "caldron_picked_up": ("state", "caldron.n.01_1", OnTop, "floor.n.01_1", False),
            "caldron_next_to_table": ("state", "caldron.n.01_1", NextTo, "table.n.02_1", True),
        },
    ),
    "cleaning_up_plates_and_food": lambda env: check_progress(
        env,
        {
            "robot_near_fridge": ("near", "agent.n.01_1", "electric_refrigerator.n.01_1"),
            "robot_near_table": ("near", "agent.n.01_1", "breakfast_table.n.01_1"),
            "robot_near_sink": ("near", "agent.n.01_1", "sink.n.01_1"),
            "fridge_opened": ("state", "electric_refrigerator.n.01_1", Open, True),
            "plate_1_picked_up": ("state", "plate.n.04_1", OnTop, "breakfast_table.n.01_1", False),
            "plate_2_picked_up": ("state", "plate.n.04_2", OnTop, "breakfast_table.n.01_1", False),
            "pizza_1_in_fridge": ("state", "pizza.n.01_1", Inside, "electric_refrigerator.n.01_1", True),
            "pizza_2_in_fridge": ("state", "pizza.n.01_2", Inside, "electric_refrigerator.n.01_1", True),
            "plate_1_in_fridge": ("state", "plate.n.04_1", Inside, "electric_refrigerator.n.01_1", True),
            "plate_2_in_fridge": ("state", "plate.n.04_2", Inside, "electric_refrigerator.n.01_1", True),
            "fridge_closed": ("state", "electric_refrigerator.n.01_1", Open, False),
            "bowl_1_picked_up": ("state", "bowl.n.01_1", OnTop, "breakfast_table.n.01_1", False),
            "bowl_2_picked_up": ("state", "bowl.n.01_2", OnTop, "breakfast_table.n.01_1", False),
            "bowl_1_in_sink": ("state", "bowl.n.01_1", Inside, "sink.n.01_1", True),
            "bowl_2_in_sink": ("state", "bowl.n.01_2", Inside, "sink.n.01_1", True),
        },
    ),
    "can_meat": lambda env: check_progress(
        env,
        {
            "robot_near_cabinet": ("near", "agent.n.01_1", "cabinet.n.01_1"),
            "robot_near_chopping_board": ("near", "agent.n.01_1", "chopping_board.n.01_1"),
            "cabinet_opened": ("state", "cabinet.n.01_1", Open, True),
            "jar_1_picked_up": ("state", "hinged_jar.n.01_1", Inside, "cabinet.n.01_1", False),
            "jar_2_picked_up": ("state", "hinged_jar.n.01_2", Inside, "cabinet.n.01_1", False),
            "jar_1_opened": ("state", "hinged_jar.n.01_1", Open, True),
            "jar_2_opened": ("state", "hinged_jar.n.01_2", Open, True),
            "bratwurst_1_picked_up": ("state", "bratwurst.n.01_1", OnTop, "chopping_board.n.01_1", False),
            "bratwurst_2_picked_up": ("state", "bratwurst.n.01_2", OnTop, "chopping_board.n.01_1", False),
            "bratwurst_3_picked_up": ("state", "bratwurst.n.01_3", OnTop, "chopping_board.n.01_1", False),
            "bratwurst_4_picked_up": ("state", "bratwurst.n.01_4", OnTop, "chopping_board.n.01_1", False),
            "bratwurst_1_in_jar": ("state", "bratwurst.n.01_1", Inside, "hinged_jar.n.01_1", True),
            "bratwurst_2_in_jar": ("state", "bratwurst.n.01_2", Inside, "hinged_jar.n.01_1", True),
            "bratwurst_3_in_jar": ("state", "bratwurst.n.01_3", Inside, "hinged_jar.n.01_2", True),
            "bratwurst_4_in_jar": ("state", "bratwurst.n.01_4", Inside, "hinged_jar.n.01_2", True),
            "jar_1_closed": ("state", "hinged_jar.n.01_1", Open, False),
            "jar_2_closed": ("state", "hinged_jar.n.01_2", Open, False),
            "jar_1_back_in_cabinet": ("state", "hinged_jar.n.01_1", Inside, "cabinet.n.01_1", True),
            "jar_2_back_in_cabinet": ("state", "hinged_jar.n.01_2", Inside, "cabinet.n.01_1", True),
            "cabinet_closed": ("state", "cabinet.n.01_1", Open, False),
        },
    ),
    "setting_mousetraps": lambda env: check_progress(
        env,
        {
            "robot_near_cabinet": ("near", "agent.n.01_1", "cabinet.n.01_1"),
            "robot_near_sink": ("near", "agent.n.01_1", "sink.n.01_1"),
            "mousetrap_1_picked_up": ("state", "mousetrap.n.01_1", OnTop, "cabinet.n.01_1", False),
            "mousetrap_2_picked_up": ("state", "mousetrap.n.01_2", OnTop, "cabinet.n.01_1", False),
            "mousetrap_3_picked_up": ("state", "mousetrap.n.01_3", OnTop, "cabinet.n.01_1", False),
            "mousetrap_4_picked_up": ("state", "mousetrap.n.01_4", OnTop, "cabinet.n.01_1", False),
            "mousetrap_1_on_floor": ("state", "mousetrap.n.01_1", OnTop, "floor.n.01_1", True),
            "mousetrap_2_on_floor": ("state", "mousetrap.n.01_2", OnTop, "floor.n.01_1", True),
            "mousetrap_3_on_floor": ("state", "mousetrap.n.01_3", OnTop, "floor.n.01_1", True),
            "mousetrap_4_on_floor": ("state", "mousetrap.n.01_4", OnTop, "floor.n.01_1", True),
            "mousetrap_1_near_sink": ("state", "mousetrap.n.01_1", Under, "sink.n.01_1", True),
            "mousetrap_2_near_sink": ("state", "mousetrap.n.01_2", Under, "sink.n.01_1", True),
        },
    ),
    "hiding_Easter_eggs": lambda env: check_progress(
        env,
        {
            "robot_near_basket": ("near", "agent.n.01_1", "wicker_basket.n.01_1"),
            "robot_near_tree": ("near", "agent.n.01_1", "tree.n.01_1"),
            "egg_1_out_of_basket": ("state", "easter_egg.n.01_1", Inside, "wicker_basket.n.01_1", False),
            "egg_2_out_of_basket": ("state", "easter_egg.n.01_2", Inside, "wicker_basket.n.01_1", False),
            "egg_3_out_of_basket": ("state", "easter_egg.n.01_3", Inside, "wicker_basket.n.01_1", False),
            "egg_1_on_lawn": ("state", "easter_egg.n.01_1", OnTop, "lawn.n.01_1", True),
            "egg_2_on_lawn": ("state", "easter_egg.n.01_2", OnTop, "lawn.n.01_1", True),
            "egg_3_on_lawn": ("state", "easter_egg.n.01_3", OnTop, "lawn.n.01_1", True),
            "egg_1_next_to_tree": ("state", "easter_egg.n.01_1", NextTo, "tree.n.01", True),
            "egg_2_next_to_tree": ("state", "easter_egg.n.01_2", NextTo, "tree.n.01", True),
            "egg_3_next_to_tree": ("state", "easter_egg.n.01_3", NextTo, "tree.n.01", True),
        },
    ),
    "picking_up_toys": lambda env: check_progress(
        env,
        {
            "robot_near_bed": ("near", "agent.n.01_1", "bed.n.01_1"),
            "robot_near_table": ("near", "agent.n.01_1", "table.n.02_1"),
            "robot_near_toy_box": ("near", "agent.n.01_1", "toy_box.n.01_1"),
            "board_game_1_picked_up": ("state", "board_game.n.01_1", OnTop, "bed.n.01_1", False),
            "board_game_2_picked_up": ("state", "board_game.n.01_2", OnTop, "bed.n.01_1", False),
            "board_game_3_picked_up": ("state", "board_game.n.01_3", OnTop, "table.n.02_1", False),
            "jigsaw_1_picked_up": ("state", "jigsaw_puzzle.n.01_1", OnTop, "table.n.02_1", False),
            "jigsaw_2_picked_up": ("state", "jigsaw_puzzle.n.01_2", OnTop, "table.n.02_1", False),
            "tennis_ball_picked_up": ("state", "tennis_ball.n.01_1", OnTop, "table.n.02_1", False),
            "board_game_1_in_box": ("state", "board_game.n.01_1", Inside, "toy_box.n.01_1", True),
            "board_game_2_in_box": ("state", "board_game.n.01_2", Inside, "toy_box.n.01_1", True),
            "board_game_3_in_box": ("state", "board_game.n.01_3", Inside, "toy_box.n.01_1", True),
            "jigsaw_1_in_box": ("state", "jigsaw_puzzle.n.01_1", Inside, "toy_box.n.01_1", True),
            "jigsaw_2_in_box": ("state", "jigsaw_puzzle.n.01_2", Inside, "toy_box.n.01_1", True),
            "tennis_ball_in_box": ("state", "tennis_ball.n.01_1", Inside, "toy_box.n.01_1", True),
        },
    ),
    "rearranging_kitchen_furniture": lambda env: check_progress(
        env,
        {
            "robot_near_countertop": ("near", "agent.n.01_1", "countertop.n.01_1"),
            "robot_near_cabinet": ("near", "agent.n.01_1", "cabinet.n.01_1"),
            "cabinet_opened": ("state", "cabinet.n.01_1", Open, True),
            "toaster_picked_up": ("state", "toaster.n.02_1", OnTop, "countertop.n.01_1", False),
            "food_processor_picked_up": ("state", "food_processor.n.01_1", OnTop, "countertop.n.01_1", False),
            "french_press_picked_up": ("state", "french_press.n.01_1", OnTop, "countertop.n.01_1", False),
            "toaster_in_cabinet": ("state", "toaster.n.02_1", Inside, "cabinet.n.01_1", True),
            "food_processor_in_cabinet": ("state", "food_processor.n.01_1", Inside, "cabinet.n.01_1", True),
            "french_press_in_cabinet": ("state", "french_press.n.01_1", Inside, "cabinet.n.01_1", True),
            "cabinet_closed": ("state", "cabinet.n.01_1", Open, False),
        },
    ),
    "putting_up_Christmas_decorations_inside": lambda env: check_progress(
        env,
        {
            "robot_near_basket": ("near", "agent.n.01_1", "wicker_basket.n.01_1"),
            "robot_near_tree": ("near", "agent.n.01_1", "christmas_tree.n.05_1"),
            "robot_near_table": ("near", "agent.n.01_1", "table.n.02_1"),
            "robot_near_sofa": ("near", "agent.n.01_1", "sofa.n.01_1"),
            "wreath_out_of_basket": ("state", "wreath.n.01_1", Inside, "wicker_basket.n.01_1", False),
            "candy_cane_1_out_of_basket": ("state", "candy_cane.n.01_1", Inside, "wicker_basket.n.01_1", False),
            "candy_cane_2_out_of_basket": ("state", "candy_cane.n.01_2", Inside, "wicker_basket.n.01_1", False),
            "candy_cane_3_out_of_basket": ("state", "candy_cane.n.01_3", Inside, "wicker_basket.n.01_1", False),
            "candle_1_out_of_basket": ("state", "pillar_candle.n.01_1", Inside, "wicker_basket.n.01_1", False),
            "candle_2_out_of_basket": ("state", "pillar_candle.n.01_2", Inside, "wicker_basket.n.01_1", False),
            "gift_1_near_tree": ("state", "gift_box.n.01_1", NextTo, "christmas_tree.n.05_1", True),
            "gift_2_near_tree": ("state", "gift_box.n.01_2", NextTo, "christmas_tree.n.05_1", True),
            "gift_3_near_tree": ("state", "gift_box.n.01_3", NextTo, "christmas_tree.n.05_1", True),
            "candle_1_on_table": ("state", "pillar_candle.n.01_1", OnTop, "table.n.02_1", True),
            "candle_2_on_table": ("state", "pillar_candle.n.01_2", OnTop, "table.n.02_1", True),
            "candy_cane_on_table": ("state", "candy_cane.n.01_1", OnTop, "table.n.02_1", True),
            "wreath_on_sofa": ("state", "wreath.n.01_1", OnTop, "sofa.n.01_1", True),
            "candy_cane_2_on_sofa": ("state", "candy_cane.n.01_2", OnTop, "sofa.n.01_1", True),
            "candy_cane_3_on_sofa": ("state", "candy_cane.n.01_3", OnTop, "sofa.n.01_1", True),
        },
    ),
    "set_up_a_coffee_station_in_your_kitchen": lambda env: check_progress(
        env,
        {
            "robot_near_countertop": ("near", "agent.n.01_1", "countertop.n.01_1"),
            "robot_near_shelf": ("near", "agent.n.01_1", "shelf.n.01_1"),
            "robot_near_coffee_maker": ("near", "agent.n.01_1", "coffee_maker.n.01_1"),
            "filter_picked_up": ("state", "paper_coffee_filter.n.01_1", OnTop, "countertop.n.01_1", False),
            "filter_in_coffee_maker": ("state", "paper_coffee_filter.n.01_1", OnTop, "coffee_maker.n.01_1", True),
            "coffee_bottle_picked_up": ("state", "bottle__of__coffee.n.01_1", OnTop, "shelf.n.01_1", False),
            "coffee_bottle_near_maker": ("state", "bottle__of__coffee.n.01_1", NextTo, "coffee_maker.n.01_1", True),
            "kettle_repositioned": ("state", "electric_kettle.n.01_1", NextTo, "coffee_maker.n.01_1", True),
            "saucer_near_maker": ("state", "saucer.n.02_1", NextTo, "coffee_maker.n.01_1", True),
            "cup_picked_up": ("state", "coffee_cup.n.01_1", OnTop, "countertop.n.01_1", False),
            "cup_on_saucer": ("state", "coffee_cup.n.01_1", OnTop, "saucer.n.02_1", True),
        },
    ),
    "putting_dishes_away_after_cleaning": lambda env: check_progress(
        env,
        {
            "robot_near_cabinet": ("near", "agent.n.01_1", "cabinet.n.01_1"),
            "robot_near_countertop_1": ("near", "agent.n.01_1", "countertop.n.01_1"),
            "robot_near_countertop_2": ("near", "agent.n.01_1", "countertop.n.01_2"),
            "cabinet_opened": ("state", "cabinet.n.01_1", Open, True),
            "plate_1_picked_up": ("state", "plate.n.04_1", OnTop, "countertop.n.01_1", False),
            "plate_2_picked_up": ("state", "plate.n.04_2", OnTop, "countertop.n.01_1", False),
            "plate_3_picked_up": ("state", "plate.n.04_3", OnTop, "countertop.n.01_1", False),
            "plate_4_picked_up": ("state", "plate.n.04_4", OnTop, "countertop.n.01_1", False),
            "plate_5_picked_up": ("state", "plate.n.04_5", OnTop, "countertop.n.01_2", False),
            "plate_6_picked_up": ("state", "plate.n.04_6", OnTop, "countertop.n.01_2", False),
            "plate_7_picked_up": ("state", "plate.n.04_7", OnTop, "countertop.n.01_2", False),
            "plate_8_picked_up": ("state", "plate.n.04_8", OnTop, "countertop.n.01_2", False),
            "plate_1_in_cabinet": ("state", "plate.n.04_1", Inside, "cabinet.n.01_1", True),
            "plate_2_in_cabinet": ("state", "plate.n.04_2", Inside, "cabinet.n.01_1", True),
            "plate_3_in_cabinet": ("state", "plate.n.04_3", Inside, "cabinet.n.01_1", True),
            "plate_4_in_cabinet": ("state", "plate.n.04_4", Inside, "cabinet.n.01_1", True),
            "plate_5_in_cabinet": ("state", "plate.n.04_5", Inside, "cabinet.n.01_1", True),
            "plate_6_in_cabinet": ("state", "plate.n.04_6", Inside, "cabinet.n.01_1", True),
            "plate_7_in_cabinet": ("state", "plate.n.04_7", Inside, "cabinet.n.01_1", True),
            "plate_8_in_cabinet": ("state", "plate.n.04_8", Inside, "cabinet.n.01_1", True),
            "cabinet_closed": ("state", "cabinet.n.01_1", Open, False),
        },
    ),
    "preparing_lunch_box": lambda env: check_progress(
        env,
        {
            "robot_near_countertop": ("near", "agent.n.01_1", "countertop.n.01_1"),
            "robot_near_chopping_board": ("near", "agent.n.01_1", "chopping_board.n.01_1"),
            "robot_near_fridge": ("near", "agent.n.01_1", "electric_refrigerator.n.01_1"),
            "lunch_box_picked_up": ("state", "packing_box.n.02_1", OnTop, "countertop.n.01_1", False),
            "sandwich_picked_up": ("state", "club_sandwich.n.01_1", OnTop, "chopping_board.n.01_1", False),
            "apple_1_picked_up": ("state", "half__apple.n.01_1", OnTop, "chopping_board.n.01_1", False),
            "apple_2_picked_up": ("state", "half__apple.n.01_2", OnTop, "chopping_board.n.01_1", False),
            "cookie_picked_up": ("state", "chocolate_chip_cookie.n.01_1", OnTop, "chopping_board.n.01_1", False),
            "fridge_opened": ("state", "electric_refrigerator.n.01_1", Open, True),
            "tea_picked_up": ("state", "bottle__of__tea.n.01_1", Inside, "electric_refrigerator.n.01_1", False),
            "sandwich_in_box": ("state", "club_sandwich.n.01_1", Inside, "packing_box.n.02_1", True),
            "apple_1_in_box": ("state", "half__apple.n.01_1", Inside, "packing_box.n.02_1", True),
            "apple_2_in_box": ("state", "half__apple.n.01_2", Inside, "packing_box.n.02_1", True),
            "cookie_in_box": ("state", "chocolate_chip_cookie.n.01_1", Inside, "packing_box.n.02_1", True),
            "tea_in_box": ("state", "bottle__of__tea.n.01_1", Inside, "packing_box.n.02_1", True),
            "fridge_closed": ("state", "electric_refrigerator.n.01_1", Open, False),
        },
    ),
    "loading_the_car": lambda env: check_progress(
        env,
        {
            "robot_near_car": ("near", "agent.n.01_1", "car.n.01_1"),
            "robot_near_table": ("near", "agent.n.01_1", "table.n.02_1"),
            "robot_near_container": ("near", "agent.n.01_1", "container.n.01_1"),
            "car_opened": ("state", "car.n.01_1", Open, True),
            "container_picked_up_floor_1": ("state", "container.n.01_1", OnTop, "floor.n.01_1", False),
            "container_picked_up_floor_2": ("state", "container.n.01_1", OnTop, "floor.n.01_2", False),
            "camera_picked_up": ("state", "digital_camera.n.01_1", OnTop, "table.n.02_1", False),
            "racket_picked_up": ("state", "tennis_racket.n.01_1", OnTop, "table.n.02_1", False),
            "container_in_car": ("state", "container.n.01_1", Inside, "car.n.01_1", True),
            "camera_in_container": ("state", "digital_camera.n.01_1", Inside, "container.n.01_1", True),
            "racket_in_car": ("state", "tennis_racket.n.01_1", Inside, "car.n.01_1", True),
            "car_closed": ("state", "car.n.01_1", Open, False),
        },
    ),
    "carrying_in_groceries": lambda env: check_progress(
        env,
        {
            "robot_near_car": ("near", "agent.n.01_1", "car.n.01_1"),
            "robot_near_fridge": ("near", "agent.n.01_1", "electric_refrigerator.n.01_1"),
            "bag_picked_up": ("state", "sack.n.01_1", Inside, "car.n.01_1", False),
            "car_closed": ("state", "car.n.01_1", Open, False),
            "tomato_out_of_bag": ("state", "beefsteak_tomato.n.01_1", Inside, "sack.n.01_1", False),
            "milk_out_of_bag": ("state", "carton__of__milk.n.01_1", Inside, "sack.n.01_1", False),
            "fridge_opened": ("state", "electric_refrigerator.n.01_1", Open, True),
            "tomato_in_fridge": ("state", "beefsteak_tomato.n.01_1", Inside, "electric_refrigerator.n.01_1", True),
            "milk_in_fridge": ("state", "carton__of__milk.n.01_1", Inside, "electric_refrigerator.n.01_1", True),
            "fridge_closed": ("state", "electric_refrigerator.n.01_1", Open, False),
        },
    ),
    "bringing_in_wood": lambda env: check_progress(
        env,
        {
            "robot_near_plywood_1": ("near", "agent.n.01_1", "plywood.n.01_1"),
            "robot_near_plywood_2": ("near", "agent.n.01_1", "plywood.n.01_2"),
            "robot_near_plywood_3": ("near", "agent.n.01_1", "plywood.n.01_3"),
            "plywood_1_picked_up": ("state", "plywood.n.01_1", OnTop, "floor.n.01_1", False),
            "plywood_2_picked_up": ("state", "plywood.n.01_2", OnTop, "floor.n.01_1", False),
            "plywood_3_picked_up": ("state", "plywood.n.01_3", OnTop, "floor.n.01_1", False),
            "plywood_1_indoors": ("state", "plywood.n.01_1", OnTop, "floor.n.01_2", True),
            "plywood_2_indoors": ("state", "plywood.n.01_2", OnTop, "floor.n.01_2", True),
            "plywood_3_indoors": ("state", "plywood.n.01_3", OnTop, "floor.n.01_2", True),
        },
    ),
    "moving_boxes_to_storage": lambda env: check_progress(
        env,
        {
            "robot_near_container_1": ("near", "agent.n.01_1", "storage_container.n.01_1"),
            "robot_near_container_2": ("near", "agent.n.01_1", "storage_container.n.01_2"),
            "robot_near_garage_floor": ("near", "agent.n.01_1", "floor.n.01_2"),
            "container_1_picked_up": ("state", "storage_container.n.01_1", OnTop, "floor.n.01_1", False),
            "container_2_picked_up": ("state", "storage_container.n.01_2", OnTop, "floor.n.01_1", False),
            "container_1_in_garage": ("state", "storage_container.n.01_1", OnTop, "floor.n.01_2", True),
            "container_2_in_garage": ("state", "storage_container.n.01_2", OnTop, "floor.n.01_2", True),
            "container_1_stacked": ("state", "storage_container.n.01_1", OnTop, "storage_container.n.01_2", True),
            "container_2_stacked": ("state", "storage_container.n.01_2", OnTop, "storage_container.n.01_1", True),
        },
    ),
    "bringing_water": lambda env: check_progress(
        env,
        {
            "robot_near_fridge": ("near", "agent.n.01_1", "electric_refrigerator.n.01_1"),
            "robot_near_coffee_table": ("near", "agent.n.01_1", "coffee_table.n.01_1"),
            "fridge_opened": ("state", "electric_refrigerator.n.01_1", Open, True),
            "bottle_1_picked_up": ("state", "bottle.n.01_1", Inside, "electric_refrigerator.n.01_1", False),
            "bottle_2_picked_up": ("state", "bottle.n.01_2", Inside, "electric_refrigerator.n.01_1", False),
            "fridge_closed": ("state", "electric_refrigerator.n.01_1", Open, False),
            "bottle_1_on_table": ("state", "bottle.n.01_1", OnTop, "coffee_table.n.01_1", True),
            "bottle_2_on_table": ("state", "bottle.n.01_2", OnTop, "coffee_table.n.01_1", True),
        },
    ),
    "tidying_bedroom": lambda env: check_progress(
        env,
        {
            "robot_near_book": ("near", "agent.n.01_1", "book.n.02_1"),
            "robot_near_sandal_1": ("near", "agent.n.01_1", "sandal.n.01_1"),
            "robot_near_sandal_2": ("near", "agent.n.01_1", "sandal.n.01_2"),
            "robot_near_bed": ("near", "agent.n.01_1", "bed.n.01_1"),
            "robot_near_table": ("near", "agent.n.01_1", "table.n.02_1"),
            "book_picked_up": ("state", "book.n.02_1", OnTop, "bed.n.01_1", False),
            "book_on_table": ("state", "book.n.02_1", OnTop, "table.n.02_1", True),
            "sandal_1_picked_up": ("state", "sandal.n.01_1", OnTop, "floor.n.01_1", False),
            "sandal_2_picked_up": ("state", "sandal.n.01_2", OnTop, "floor.n.01_1", False),
            "sandal_1_near_bed": ("state", "sandal.n.01_1", NextTo, "bed.n.01_1", True),
            "sandal_2_near_sandal_1": ("state", "sandal.n.01_2", NextTo, "sandal.n.01_1", True),
        },
    ),
    "outfit_a_basic_toolbox": lambda env: check_progress(
        env,
        {
            "robot_near_toolbox": ("near", "agent.n.01_1", "toolbox.n.01_1"),
            "toolbox_opened": ("state", "toolbox.n.01_1", Open, True),
            "drill_picked_up": ("state", "drill.n.01_1", OnTop, "tabletop.n.01_1", False),
            "pliers_picked_up": ("state", "pliers.n.01_1", OnTop, "tabletop.n.01_1", False),
            "flashlight_picked_up": ("state", "flashlight.n.01_1", OnTop, "tabletop.n.01_1", False),
            "wrench_picked_up": ("state", "allen_wrench.n.01_1", OnTop, "tabletop.n.01_1", False),
            "screwdriver_picked_up": ("state", "screwdriver.n.01_1", OnTop, "tabletop.n.01_1", False),
            "drill_in_toolbox": ("state", "drill.n.01_1", Inside, "toolbox.n.01_1", True),
            "pliers_in_toolbox": ("state", "pliers.n.01_1", Inside, "toolbox.n.01_1", True),
            "flashlight_in_toolbox": ("state", "flashlight.n.01_1", Inside, "toolbox.n.01_1", True),
            "wrench_in_toolbox": ("state", "allen_wrench.n.01_1", Inside, "toolbox.n.01_1", True),
            "screwdriver_in_toolbox": ("state", "screwdriver.n.01_1", Inside, "toolbox.n.01_1", True),
            "toolbox_closed": ("state", "toolbox.n.01_1", Open, False),
        },
    ),
    "sorting_vegetables": lambda env: check_progress(
        env,
        {
            "robot_near_basket_1": ("near", "agent.n.01_1", "wicker_basket.n.01_1"),
            "robot_near_basket_2": ("near", "agent.n.01_1", "wicker_basket.n.01_2"),
            "robot_near_bowls": ("near", "agent.n.01_1", "countertop.n.01_1"),
            "basket_1_picked_up": ("state", "wicker_basket.n.01_1", OnTop, "floor.n.01_1", False),
            "basket_2_picked_up": ("state", "wicker_basket.n.01_2", OnTop, "floor.n.01_1", False),
            "bok_choy_1_sorted": ("state", "bok_choy.n.02_1", Inside, "mixing_bowl.n.01_2", True),
            "bok_choy_2_sorted": ("state", "bok_choy.n.02_2", Inside, "mixing_bowl.n.01_2", True),
            "bok_choy_3_sorted": ("state", "bok_choy.n.02_3", Inside, "mixing_bowl.n.01_2", True),
            "onion_1_sorted": ("state", "vidalia_onion.n.01_1", Inside, "mixing_bowl.n.01_2", True),
            "onion_2_sorted": ("state", "vidalia_onion.n.01_2", Inside, "mixing_bowl.n.01_2", True),
            "onion_3_sorted": ("state", "vidalia_onion.n.01_3", Inside, "mixing_bowl.n.01_2", True),
            "leek_1_sorted": ("state", "leek.n.02_1", Inside, "mixing_bowl.n.01_1", True),
            "leek_2_sorted": ("state", "leek.n.02_2", Inside, "mixing_bowl.n.01_1", True),
            "broccoli_1_sorted": ("state", "broccoli.n.02_1", Inside, "mixing_bowl.n.01_1", True),
            "broccoli_2_sorted": ("state", "broccoli.n.02_2", Inside, "mixing_bowl.n.01_1", True),
            "corn_1_sorted": ("state", "sweet_corn.n.02_1", Inside, "mixing_bowl.n.01_3", True),
            "corn_2_sorted": ("state", "sweet_corn.n.02_2", Inside, "mixing_bowl.n.01_3", True),
            "corn_3_sorted": ("state", "sweet_corn.n.02_3", Inside, "mixing_bowl.n.01_3", True),
        },
    ),
    "collecting_childrens_toys": lambda env: check_progress(
        env,
        {
            "robot_near_teddy_1": ("near", "agent.n.01_1", "teddy.n.01_1"),
            "robot_near_teddy_2": ("near", "agent.n.01_1", "teddy.n.01_2"),
            "robot_near_die_1": ("near", "agent.n.01_1", "die.n.01_1"),
            "robot_near_die_2": ("near", "agent.n.01_1", "die.n.01_2"),
            "robot_near_board_game_1": ("near", "agent.n.01_1", "board_game.n.01_1"),
            "robot_near_board_game_2": ("near", "agent.n.01_1", "board_game.n.01_2"),
            "robot_near_train": ("near", "agent.n.01_1", "train_set.n.01_1"),
            "robot_near_bookcase": ("near", "agent.n.01_1", "bookcase.n.01_1"),
            "teddy_1_picked_up": ("state", "teddy.n.01_1", OnTop, "floor.n.01_1", False),
            "teddy_2_picked_up": ("state", "teddy.n.01_2", OnTop, "floor.n.01_1", False),
            "die_1_picked_up": ("state", "die.n.01_1", OnTop, "bed.n.01_1", False),
            "die_2_picked_up": ("state", "die.n.01_2", OnTop, "bed.n.01_1", False),
            "board_game_1_picked_up": ("state", "board_game.n.01_1", OnTop, "desk.n.01_1", False),
            "board_game_2_picked_up": ("state", "board_game.n.01_2", OnTop, "bed.n.01_1", False),
            "train_picked_up": ("state", "train_set.n.01_1", OnTop, "desk.n.01_1", False),
            "teddy_1_in_bookcase": ("state", "teddy.n.01_1", Inside, "bookcase.n.01_1", True),
            "teddy_2_in_bookcase": ("state", "teddy.n.01_2", Inside, "bookcase.n.01_1", True),
            "die_1_in_bookcase": ("state", "die.n.01_1", Inside, "bookcase.n.01_1", True),
            "die_2_in_bookcase": ("state", "die.n.01_2", Inside, "bookcase.n.01_1", True),
            "board_game_1_in_bookcase": ("state", "board_game.n.01_1", Inside, "bookcase.n.01_1", True),
            "board_game_2_in_bookcase": ("state", "board_game.n.01_2", Inside, "bookcase.n.01_1", True),
        },
    ),
    "putting_shoes_on_rack": lambda env: check_progress(
        env,
        {
            "robot_near_gym_shoe_1": ("near", "agent.n.01_1", "gym_shoe.n.01_1"),
            "robot_near_gym_shoe_2": ("near", "agent.n.01_1", "gym_shoe.n.01_2"),
            "robot_near_sandal_1": ("near", "agent.n.01_1", "sandal.n.01_1"),
            "robot_near_sandal_2": ("near", "agent.n.01_1", "sandal.n.01_2"),
            "robot_near_hallstand": ("near", "agent.n.01_1", "hallstand.n.01_1"),
            "gym_shoe_1_picked_up": ("state", "gym_shoe.n.01_1", OnTop, "floor.n.01_1", False),
            "gym_shoe_2_picked_up": ("state", "gym_shoe.n.01_2", OnTop, "floor.n.01_1", False),
            "sandal_1_picked_up": ("state", "sandal.n.01_1", OnTop, "floor.n.01_1", False),
            "sandal_2_picked_up": ("state", "sandal.n.01_2", OnTop, "floor.n.01_1", False),
            "gym_shoe_1_on_rack": ("state", "gym_shoe.n.01_1", Touching, "hallstand.n.01_1", True),
            "gym_shoe_2_on_rack": ("state", "gym_shoe.n.01_2", Touching, "hallstand.n.01_1", True),
            "sandal_1_on_rack": ("state", "sandal.n.01_1", Touching, "hallstand.n.01_1", True),
            "sandal_2_on_rack": ("state", "sandal.n.01_2", Touching, "hallstand.n.01_1", True),
            "gym_shoes_paired": ("state", "gym_shoe.n.01_1", NextTo, "gym_shoe.n.01_2", True),
            "sandals_paired": ("state", "sandal.n.01_1", NextTo, "sandal.n.01_2", True),
        },
    ),
    "boxing_books_up_for_storage": lambda env: check_progress(
        env,
        {
            "robot_near_box": ("near", "agent.n.01_1", "box.n.01_1"),
            "book_1_retrieved": ("state", "book.n.02_1", Inside, "bookcase.n.01", False),
            "book_2_retrieved": ("state", "book.n.02_2", Inside, "bookcase.n.01", False),
            "book_3_retrieved": ("state", "book.n.02_3", Inside, "bookcase.n.01", False),
            "book_4_retrieved": ("state", "book.n.02_4", Inside, "bookcase.n.01", False),
            "book_5_retrieved": ("state", "book.n.02_5", Inside, "bookcase.n.01", False),
            "book_6_retrieved": ("state", "book.n.02_6", Inside, "bookcase.n.01", False),
            "book_1_in_box": ("state", "book.n.02_1", Inside, "box.n.01_1", True),
            "book_2_in_box": ("state", "book.n.02_2", Inside, "box.n.01_1", True),
            "book_3_in_box": ("state", "book.n.02_3", Inside, "box.n.01_1", True),
            "book_4_in_box": ("state", "book.n.02_4", Inside, "box.n.01_1", True),
            "book_5_in_box": ("state", "book.n.02_5", Inside, "box.n.01_1", True),
            "book_6_in_box": ("state", "book.n.02_6", Inside, "box.n.01_1", True),
        },
    ),
    "storing_food": lambda env: check_progress(
        env,
        {
            "robot_near_cabinet": ("near", "agent.n.01_1", "cabinet.n.01_1"),
            "robot_near_countertop": ("near", "agent.n.01_1", "countertop.n.01_1"),
            "cabinet_opened": ("state", "cabinet.n.01_1", Open, True),
            "chips_1_picked_up": ("state", "bag__of__chips.n.01_1", OnTop, "countertop.n.01_1", False),
            "chips_2_picked_up": ("state", "bag__of__chips.n.01_2", OnTop, "countertop.n.01_1", False),
            "oil_1_picked_up": ("state", "bottle__of__olive_oil.n.01_1", OnTop, "countertop.n.01_1", False),
            "oil_2_picked_up": ("state", "bottle__of__olive_oil.n.01_2", OnTop, "countertop.n.01_1", False),
            "sugar_1_picked_up": ("state", "jar__of__sugar.n.01_1", OnTop, "countertop.n.01_1", False),
            "sugar_2_picked_up": ("state", "jar__of__sugar.n.01_2", OnTop, "countertop.n.01_1", False),
            "oatmeal_1_picked_up": ("state", "box__of__oatmeal.n.01_1", OnTop, "countertop.n.01_1", False),
            "oatmeal_2_picked_up": ("state", "box__of__oatmeal.n.01_2", OnTop, "countertop.n.01_1", False),
            "chips_1_stored": ("state", "bag__of__chips.n.01_1", Inside, "cabinet.n.01_1", True),
            "chips_2_stored": ("state", "bag__of__chips.n.01_2", Inside, "cabinet.n.01_1", True),
            "oil_1_stored": ("state", "bottle__of__olive_oil.n.01_1", Inside, "cabinet.n.01_1", True),
            "oil_2_stored": ("state", "bottle__of__olive_oil.n.01_2", Inside, "cabinet.n.01_1", True),
            "sugar_1_stored": ("state", "jar__of__sugar.n.01_1", Inside, "cabinet.n.01_1", True),
            "sugar_2_stored": ("state", "jar__of__sugar.n.01_2", Inside, "cabinet.n.01_1", True),
            "oatmeal_1_stored": ("state", "box__of__oatmeal.n.01_1", Inside, "cabinet.n.01_1", True),
            "oatmeal_2_stored": ("state", "box__of__oatmeal.n.01_2", Inside, "cabinet.n.01_1", True),
            "cabinet_closed": ("state", "cabinet.n.01_1", Open, False),
        },
    ),
    "clearing_food_from_table_into_fridge": lambda env: check_progress(
        env,
        {
            "robot_near_countertop": ("near", "agent.n.01_1", "countertop.n.01_1"),
            "robot_near_table": ("near", "agent.n.01_1", "breakfast_table.n.01_1"),
            "robot_near_fridge": ("near", "agent.n.01_1", "electric_refrigerator.n.01_1"),
            "tupperware_1_picked_up": ("state", "tupperware.n.01_1", OnTop, "countertop.n.01_1", False),
            "tupperware_2_picked_up": ("state", "tupperware.n.01_2", OnTop, "countertop.n.01_1", False),
            "chicken_picked_up": ("state", "half__chicken.n.01_1", OnTop, "plate.n.04_1", False),
            "pie_picked_up": ("state", "half__apple_pie.n.01_1", OnTop, "plate.n.04_2", False),
            "chicken_in_tupperware": ("state", "half__chicken.n.01_1", Inside, "tupperware.n.01_1", True),
            "pie_in_tupperware": ("state", "half__apple_pie.n.01_1", Inside, "tupperware.n.01_2", True),
            "fridge_opened": ("state", "electric_refrigerator.n.01_1", Open, True),
            "tupperware_1_in_fridge": ("state", "tupperware.n.01_1", Inside, "electric_refrigerator.n.01_1", True),
            "tupperware_2_in_fridge": ("state", "tupperware.n.01_2", Inside, "electric_refrigerator.n.01_1", True),
            "fridge_closed": ("state", "electric_refrigerator.n.01_1", Open, False),
        },
    ),
    "assembling_gift_baskets": lambda env: check_progress(
        env,
        {
            "robot_near_table": ("near", "agent.n.01_1", "table.n.02_1"),
            "basket_1_picked_up": ("state", "wicker_basket.n.01_1", OnTop, "floor.n.01_1", False),
            "basket_2_picked_up": ("state", "wicker_basket.n.01_2", OnTop, "floor.n.01_1", False),
            "basket_3_picked_up": ("state", "wicker_basket.n.01_3", OnTop, "floor.n.01_1", False),
            "basket_4_picked_up": ("state", "wicker_basket.n.01_4", OnTop, "floor.n.01_1", False),
            "candle_1_in_basket": ("state", "candle.n.01_1", Inside, "wicker_basket.n.01", True),
            "candle_2_in_basket": ("state", "candle.n.01_2", Inside, "wicker_basket.n.01", True),
            "candle_3_in_basket": ("state", "candle.n.01_3", Inside, "wicker_basket.n.01", True),
            "candle_4_in_basket": ("state", "candle.n.01_4", Inside, "wicker_basket.n.01", True),
            "cookie_1_in_basket": ("state", "butter_cookie.n.01_1", Inside, "wicker_basket.n.01", True),
            "cookie_2_in_basket": ("state", "butter_cookie.n.01_2", Inside, "wicker_basket.n.01", True),
            "cookie_3_in_basket": ("state", "butter_cookie.n.01_3", Inside, "wicker_basket.n.01", True),
            "cookie_4_in_basket": ("state", "butter_cookie.n.01_4", Inside, "wicker_basket.n.01", True),
            "cheese_1_in_basket": ("state", "swiss_cheese.n.01_1", Inside, "wicker_basket.n.01", True),
            "cheese_2_in_basket": ("state", "swiss_cheese.n.01_2", Inside, "wicker_basket.n.01", True),
            "cheese_3_in_basket": ("state", "swiss_cheese.n.01_3", Inside, "wicker_basket.n.01", True),
            "cheese_4_in_basket": ("state", "swiss_cheese.n.01_4", Inside, "wicker_basket.n.01", True),
            "bow_1_in_basket": ("state", "bow.n.08_1", OnTop, "wicker_basket.n.01", True),
            "bow_2_in_basket": ("state", "bow.n.08_2", OnTop, "wicker_basket.n.01", True),
            "bow_3_in_basket": ("state", "bow.n.08_3", OnTop, "wicker_basket.n.01", True),
            "bow_4_in_basket": ("state", "bow.n.08_4", OnTop, "wicker_basket.n.01", True),
        },
    ),
    "sorting_household_items": lambda env: check_progress(
        env,
        {
            "robot_near_basket_1": ("near", "agent.n.01_1", "basket.n.01_1"),
            "robot_near_basket_2": ("near", "agent.n.01_1", "basket.n.01_2"),
            "robot_near_sink": ("near", "agent.n.01_1", "sink.n.01_1"),
            "robot_near_shelf": ("near", "agent.n.01_1", "shelf.n.01_1"),
            "detergent_1_picked_up": ("state", "bottle__of__detergent.n.01_1", Inside, "basket.n.01_1", False),
            "detergent_2_picked_up": ("state", "bottle__of__detergent.n.01_2", Inside, "basket.n.01_1", False),
            "sanitary_napkins_picked_up": ("state", "box__of__sanitary_napkin.n.01_1", Inside, "basket.n.01_1", False),
            "soap_dispenser_picked_up": ("state", "soap_dispenser.n.01_1", Inside, "basket.n.01_2", False),
            "toothpaste_picked_up": ("state", "tube__of__toothpaste.n.01_1", Inside, "basket.n.01_2", False),
            "toothbrush_picked_up": ("state", "toothbrush.n.01_1", Inside, "basket.n.01_2", False),
            "detergent_1_under_sink": ("state", "bottle__of__detergent.n.01_1", Under, "sink.n.01_1", True),
            "detergent_2_under_sink": ("state", "bottle__of__detergent.n.01_2", Under, "sink.n.01_1", True),
            "detergents_together": (
                "state",
                "bottle__of__detergent.n.01_1",
                NextTo,
                "bottle__of__detergent.n.01_2",
                True,
            ),
            "sanitary_napkins_on_shelf": ("state", "box__of__sanitary_napkin.n.01_1", OnTop, "shelf.n.01_1", True),
            "soap_dispenser_on_sink": ("state", "soap_dispenser.n.01_1", OnTop, "sink.n.01_1", True),
            "toothbrush_in_cup": ("state", "toothbrush.n.01_1", Inside, "cup.n.01_1", True),
            "toothpaste_near_cup": ("state", "tube__of__toothpaste.n.01_1", NextTo, "cup.n.01_1", True),
        },
    ),
    "getting_organized_for_work": lambda env: check_progress(
        env,
        {
            "robot_near_chair": ("near", "agent.n.01_1", "swivel_chair.n.01_1"),
            "robot_near_desk": ("near", "agent.n.01_1", "desk.n.01_1"),
            "chair_near_desk": ("state", "swivel_chair.n.01_1", NextTo, "desk.n.01_1", True),
            "keyboard_picked_up": ("state", "keyboard.n.01_1", OnTop, "notebook.n.01_1", False),
            "keyboard_on_desk": ("state", "keyboard.n.01_1", OnTop, "desk.n.01_1", True),
            "keyboard_near_monitor": ("state", "keyboard.n.01_1", NextTo, "monitor.n.04_1", True),
            "mouse_on_desk": ("state", "mouse.n.04_1", OnTop, "desk.n.01_1", True),
            "mouse_near_keyboard": ("state", "mouse.n.04_1", NextTo, "keyboard.n.01_1", True),
            "pen_picked_up": ("state", "pen.n.01_1", OnTop, "folder.n.02_1", False),
            "folder_picked_up": ("state", "folder.n.02_1", OnTop, "swivel_chair.n.01_1", False),
            "folder_on_desk": ("state", "folder.n.02_1", OnTop, "desk.n.01_1", True),
            "folder_near_mouse": ("state", "folder.n.02_1", NextTo, "mouse.n.04_1", True),
            "notebook_on_folder": ("state", "notebook.n.01_1", OnTop, "folder.n.02_1", True),
            "pen_on_notebook": ("state", "pen.n.01_1", OnTop, "notebook.n.01_1", True),
        },
    ),
    "clean_up_your_desk": lambda env: check_progress(
        env,
        {
            "robot_near_chair": ("near", "agent.n.01_1", "chair.n.01_1"),
            "robot_near_desk": ("near", "agent.n.01_1", "desk.n.01_1"),
            "robot_near_bookcase": ("near", "agent.n.01_1", "bookcase.n.01_1"),
            "robot_near_bed": ("near", "agent.n.01_1", "bed.n.01_1"),
            "folder_1_picked_up": ("state", "folder.n.02_1", OnTop, "desk.n.01_1", False),
            "folder_2_picked_up": ("state", "folder.n.02_2", OnTop, "chair.n.01_1", False),
            "folder_1_in_bookcase": ("state", "folder.n.02_1", Inside, "bookcase.n.01_1", True),
            "folder_2_in_bookcase": ("state", "folder.n.02_2", Inside, "bookcase.n.01_1", True),
            "pen_1_picked_up": ("state", "pen.n.01_1", OnTop, "desk.n.01_1", False),
            "pen_2_picked_up": ("state", "pen.n.01_2", OnTop, "desk.n.01_1", False),
            "pencil_picked_up": ("state", "pencil.n.01_1", OnTop, "desk.n.01_1", False),
            "pen_1_in_box": ("state", "pen.n.01_1", Inside, "pencil_box.n.01_1", True),
            "pen_2_in_box": ("state", "pen.n.01_2", Inside, "pencil_box.n.01_1", True),
            "pencil_in_box": ("state", "pencil.n.01_1", Inside, "pencil_box.n.01_1", True),
            "book_1_picked_up": ("state", "paperback_book.n.01_1", OnTop, "desk.n.01_1", False),
            "book_2_picked_up": ("state", "paperback_book.n.01_2", OnTop, "desk.n.01_1", False),
            "book_1_in_bookcase": ("state", "paperback_book.n.01_1", Inside, "bookcase.n.01_1", True),
            "book_2_in_bookcase": ("state", "paperback_book.n.01_2", Inside, "bookcase.n.01_1", True),
            "stapler_picked_up": ("state", "stapler.n.01_1", Inside, "bookcase.n.01_1", False),
            "stapler_on_desk": ("state", "stapler.n.01_1", OnTop, "desk.n.01_1", True),
            "laptop_picked_up": ("state", "laptop.n.01_1", OnTop, "bed.n.01_1", False),
            "laptop_on_desk": ("state", "laptop.n.01_1", OnTop, "desk.n.01_1", True),
            "laptop_closed": ("state", "laptop.n.01_1", Open, False),
        },
    ),
    "setting_the_fire": lambda env: check_progress(
        env,
        {
            "robot_near_table": ("near", "agent.n.01_1", "table.n.02_1"),
            "robot_near_fireplace": ("near", "agent.n.01_1", "wood_fireplace.n.01_1"),
            "newspaper_picked_up": ("state", "newspaper.n.03_1", OnTop, "table.n.02_1", False),
            "lighter_picked_up": ("state", "cigar_lighter.n.01_1", OnTop, "table.n.02_1", False),
            "firewood_1_picked_up": ("state", "firewood.n.01_1", OnTop, "floor.n.01_1", False),
            "firewood_2_picked_up": ("state", "firewood.n.01_2", OnTop, "floor.n.01_1", False),
            "newspaper_in_fireplace": ("state", "newspaper.n.03_1", Inside, "wood_fireplace.n.01_1", True),
            "firewood_1_in_fireplace": ("state", "firewood.n.01_1", Inside, "wood_fireplace.n.01_1", True),
            "firewood_2_in_fireplace": ("state", "firewood.n.01_2", Inside, "wood_fireplace.n.01_1", True),
            "lighter_on": ("state", "cigar_lighter.n.01_1", ToggledOn, True),
            "newspaper_on_fire": ("state", "newspaper.n.03_1", OnFire, True),
            "firewood_1_on_fire": ("state", "firewood.n.01_1", OnFire, True),
            "firewood_2_on_fire": ("state", "firewood.n.01_2", OnFire, True),
            "firewood_1_on_newspaper": ("state", "firewood.n.01_1", OnTop, "newspaper.n.03_1", True),
            "firewood_2_on_newspaper": ("state", "firewood.n.01_2", OnTop, "newspaper.n.03_1", True),
            "lighter_off": ("state", "cigar_lighter.n.01_1", ToggledOn, False),
        },
    ),
    "clean_boxing_gloves": lambda env: check_progress(
        env,
        {
            "robot_near_washer": ("near", "agent.n.01_1", "washer.n.03_1"),
            "robot_near_countertop": ("near", "agent.n.01_1", "countertop.n.01_1"),
            "washer_opened": ("state", "washer.n.03_1", Open, True),
            "glove_1_picked_up": ("state", "boxing_glove.n.01_1", OnTop, "countertop.n.01_1", False),
            "glove_2_picked_up": ("state", "boxing_glove.n.01_2", OnTop, "countertop.n.01_1", False),
            "glove_1_in_washer": ("state", "boxing_glove.n.01_1", Inside, "washer.n.03_1", True),
            "glove_2_in_washer": ("state", "boxing_glove.n.01_2", Inside, "washer.n.03_1", True),
            "washer_closed": ("state", "washer.n.03_1", Open, False),
            "washer_turned_on": ("state", "washer.n.03_1", ToggledOn, True),
            "glove_1_clean": ("state", "boxing_glove.n.01_1", Covered, "dust.n.01_1", False),
            "glove_2_clean": ("state", "boxing_glove.n.01_2", Covered, "dust.n.01_1", False),
        },
    ),
    "wash_a_baseball_cap": lambda env: check_progress(
        env,
        {
            "robot_near_washer": ("near", "agent.n.01_1", "washer.n.03_1"),
            "robot_near_countertop": ("near", "agent.n.01_1", "countertop.n.01_1"),
            "washer_opened": ("state", "washer.n.03_1", Open, True),
            "cap_1_picked_up": ("state", "baseball_cap.n.01_1", OnTop, "countertop.n.01_1", False),
            "cap_2_picked_up": ("state", "baseball_cap.n.01_2", OnTop, "countertop.n.01_1", False),
            "cap_1_in_washer": ("state", "baseball_cap.n.01_1", Inside, "washer.n.03_1", True),
            "cap_2_in_washer": ("state", "baseball_cap.n.01_2", Inside, "washer.n.03_1", True),
            "washer_closed": ("state", "washer.n.03_1", Open, False),
            "washer_turned_on": ("state", "washer.n.03_1", ToggledOn, True),
            "cap_1_clean": ("state", "baseball_cap.n.01_1", Covered, "dirt.n.02_1", False),
            "cap_2_clean": ("state", "baseball_cap.n.01_2", Covered, "dirt.n.02_1", False),
        },
    ),
    "wash_dog_toys": lambda env: check_progress(
        env,
        {
            "robot_near_washer": ("near", "agent.n.01_1", "washer.n.03_1"),
            "robot_near_cabinet": ("near", "agent.n.01_1", "cabinet.n.01_1"),
            "washer_opened": ("state", "washer.n.03_1", Open, True),
            "cabinet_opened": ("state", "cabinet.n.01_1", Open, True),
            "teddy_1_picked_up": ("state", "teddy.n.01_1", Inside, "cabinet.n.01_1", False),
            "teddy_2_picked_up": ("state", "teddy.n.01_2", Inside, "cabinet.n.01_1", False),
            "tennis_ball_picked_up": ("state", "tennis_ball.n.01_1", Inside, "cabinet.n.01_1", False),
            "softball_picked_up": ("state", "softball.n.01_1", Inside, "cabinet.n.01_1", False),
            "teddy_1_in_washer": ("state", "teddy.n.01_1", Inside, "washer.n.03_1", True),
            "teddy_2_in_washer": ("state", "teddy.n.01_2", Inside, "washer.n.03_1", True),
            "tennis_ball_in_washer": ("state", "tennis_ball.n.01_1", Inside, "washer.n.03_1", True),
            "softball_in_washer": ("state", "softball.n.01_1", Inside, "washer.n.03_1", True),
            "washer_closed": ("state", "washer.n.03_1", Open, False),
            "washer_turned_on": ("state", "washer.n.03_1", ToggledOn, True),
            "teddy_1_clean_dirt": ("state", "teddy.n.01_1", Covered, "dirt.n.02_1", False),
            "teddy_2_clean_dust": ("state", "teddy.n.01_2", Covered, "dust.n.01_1", False),
            "tennis_ball_clean": ("state", "tennis_ball.n.01_1", Covered, "debris.n.01_1", False),
            "softball_clean": ("state", "softball.n.01_1", Covered, "dirt.n.02_1", False),
        },
    ),
    "hanging_pictures": lambda env: check_progress(
        env,
        {
            "robot_near_countertop": ("near", "agent.n.01_1", "countertop.n.01_1"),
            "robot_near_wall_nail": ("near", "agent.n.01_1", "wall_nail.n.01_1"),
            "poster_picked_up": ("state", "poster.n.01_1", OnTop, "countertop.n.01_1", False),
            "poster_attached_to_nail": ("state", "poster.n.01_1", AttachedTo, "wall_nail.n.01_1", True),
        },
    ),
    "attach_a_camera_to_a_tripod": lambda env: check_progress(
        env,
        {
            "robot_near_camera": ("near", "agent.n.01_1", "digital_camera.n.01_1"),
            "robot_near_tripod": ("near", "agent.n.01_1", "camera_tripod.n.01_1"),
            "camera_picked_up": ("state", "digital_camera.n.01_1", OnTop, "floor.n.01_1", False),
            "tripod_picked_up": ("state", "camera_tripod.n.01_1", OnTop, "floor.n.01_1", False),
            "camera_attached_to_tripod": ("state", "digital_camera.n.01_1", AttachedTo, "camera_tripod.n.01_1", True),
        },
    ),
    "clean_a_patio": lambda env: check_progress(
        env,
        {
            "robot_near_broom": ("near", "agent.n.01_1", "broom.n.01_1"),
            "broom_picked_up": ("state", "broom.n.01_1", OnTop, "floor.n.01_1", False),
            "floor_completely_clean": ("state", "floor.n.01_1", Covered, "mud.n.03_1", False),
        },
    ),
    "clean_a_trumpet": lambda env: check_progress(
        env,
        {
            "robot_near_desk": ("near", "agent.n.01_1", "desk.n.01_1"),
            "robot_near_scrub_brush": ("near", "agent.n.01_1", "scrub_brush.n.01_1"),
            "robot_near_cornet": ("near", "agent.n.01_1", "cornet.n.01_1"),
            "scrub_brush_picked_up": ("state", "scrub_brush.n.01_1", OnTop, "desk.n.01_1", False),
            "cornet_completely_clean": ("state", "cornet.n.01_1", Covered, "dust.n.01_1", False),
        },
    ),
    "spraying_for_bugs": lambda env: check_progress(
        env,
        {
            "robot_near_atomizer": ("near", "agent.n.01_1", "insectifuge__atomizer.n.01_1"),
            "robot_near_plant_1": ("near", "agent.n.01_1", "pot_plant.n.01_1"),
            "robot_near_plant_2": ("near", "agent.n.01_1", "pot_plant.n.01_2"),
            "atomizer_picked_up": ("state", "insectifuge__atomizer.n.01_1", OnTop, "floor.n.01_1", False),
            "atomizer_turned_on": ("state", "insectifuge__atomizer.n.01_1", ToggledOn, True),
            "plant_1_covered": ("state", "pot_plant.n.01_1", Covered, "insectifuge.n.01_1", True),
            "plant_2_covered": ("state", "pot_plant.n.01_2", Covered, "insectifuge.n.01_1", True),
            "atomizer_turned_off": ("state", "insectifuge__atomizer.n.01_1", ToggledOn, False),
        },
    ),
    "spraying_fruit_trees": lambda env: check_progress(
        env,
        {
            "robot_near_atomizer": ("near", "agent.n.01_1", "pesticide__atomizer.n.01_1"),
            "robot_near_tree_1": ("near", "agent.n.01_1", "tree.n.01_1"),
            "robot_near_tree_2": ("near", "agent.n.01_1", "tree.n.01_2"),
            "atomizer_picked_up": ("state", "pesticide__atomizer.n.01_1", OnTop, "floor.n.01_1", False),
            "atomizer_turned_on": ("state", "pesticide__atomizer.n.01_1", ToggledOn, True),
            "tree_1_covered": ("state", "tree.n.01_1", Covered, "pesticide.n.01_1", True),
            "tree_2_covered": ("state", "tree.n.01_2", Covered, "pesticide.n.01_1", True),
            "atomizer_turned_off": ("state", "pesticide__atomizer.n.01_1", ToggledOn, False),
        },
    ),
    "make_microwave_popcorn": lambda env: check_progress(
        env,
        {
            "robot_near_microwave": ("near", "agent.n.01_1", "microwave.n.02_1"),
            "robot_near_countertop": ("near", "agent.n.01_1", "countertop.n.01_1"),
            "microwave_opened": ("state", "microwave.n.02_1", Open, True),
            "popcorn_bag_picked_up": ("state", "popcorn__bag.n.01_1", OnTop, "countertop.n.01_1", False),
            "popcorn_bag_in_microwave": ("state", "popcorn__bag.n.01_1", Inside, "microwave.n.02_1", True),
            "microwave_closed": ("state", "microwave.n.02_1", Open, False),
            "microwave_turned_on": ("state", "microwave.n.02_1", ToggledOn, True),
            "popcorn_cooked": ("exists", "cooked__popcorn.n.01_1", True),
        },
    ),
    "cook_cabbage": lambda env: check_progress(
        env,
        {
            "robot_near_fridge": ("near", "agent.n.01_1", "electric_refrigerator.n.01_1"),
            "robot_near_countertop": ("near", "agent.n.01_1", "countertop.n.01_1"),
            "robot_near_stove": ("near", "agent.n.01_1", "stove.n.01_1"),
            "fridge_opened": ("state", "electric_refrigerator.n.01_1", Open, True),
            "cabbage_picked_up": ("state", "head_cabbage.n.02_1", Inside, "electric_refrigerator.n.01_1", False),
            "chili_picked_up": ("state", "chili.n.02_1", Inside, "electric_refrigerator.n.01_1", False),
            "fridge_closed": ("state", "electric_refrigerator.n.01_1", Open, False),
            "cabbage_on_board": ("state", "head_cabbage.n.02_1", OnTop, "chopping_board.n.01_1", True),
            "chili_on_board": ("state", "chili.n.02_1", OnTop, "chopping_board.n.01_1", True),
            "pan_on_stove": ("state", "frying_pan.n.01_1", OnTop, "stove.n.01_1", True),
            "cabbage_diced": ("exists", "head_cabbage.n.02_1", False),
            "chili_diced": ("exists", "chili.n.02_1", False),
            "cabbage_in_pan": ("state", "frying_pan.n.01_1", Contains, "cooked__diced__head_cabbage.n.01_1", True),
            "chili_in_pan": ("state", "frying_pan.n.01_1", Contains, "cooked__diced__chili.n.01_1", True),
            "stove_on": ("state", "stove.n.01_1", ToggledOn, True),
        },
    ),
    "chop_an_onion": lambda env: check_progress(
        env,
        {
            "robot_near_countertop": ("near", "agent.n.01_1", "countertop.n.01_1"),
            "robot_near_sink": ("near", "agent.n.01_1", "sink.n.01_1"),
            "board_picked_up": ("state", "chopping_board.n.01_1", OnTop, "countertop.n.01_1", False),
            "board_placed_near_sink": ("state", "chopping_board.n.01_1", NextTo, "sink.n.01_1", True),
            "parer_picked_up": ("state", "parer.n.02_1", OnTop, "countertop.n.01_1", False),
            "onion_picked_up": ("state", "vidalia_onion.n.01_1", Inside, "sink.n.01_1", False),
            "onion_on_board": ("state", "vidalia_onion.n.01_1", OnTop, "chopping_board.n.01_1", True),
            "onion_diced": ("exists", "diced__vidalia_onion.n.01_1", True),
            "diced_onion_in_bowl": ("state", "bowl.n.01_1", Contains, "diced__vidalia_onion.n.01_1", True),
            "parer_in_sink": ("state", "parer.n.02_1", Inside, "sink.n.01_1", True),
            "board_in_sink": ("state", "chopping_board.n.01_1", Inside, "sink.n.01_1", True),
        },
    ),
    "slicing_vegetables": lambda env: check_progress(
        env,
        {
            "robot_near_fridge": ("near", "agent.n.01_1", "electric_refrigerator.n.01_1"),
            "robot_near_countertop": ("near", "agent.n.01_1", "countertop.n.01_1"),
            "fridge_opened": ("state", "electric_refrigerator.n.01_1", Open, True),
            "pepper_1_retrieved": ("state", "bell_pepper.n.02_1", Inside, "electric_refrigerator.n.01_1", False),
            "pepper_2_retrieved": ("state", "bell_pepper.n.02_2", Inside, "electric_refrigerator.n.01_1", False),
            "beet_1_retrieved": ("state", "beet.n.02_1", Inside, "electric_refrigerator.n.01_1", False),
            "beet_2_retrieved": ("state", "beet.n.02_2", Inside, "electric_refrigerator.n.01_1", False),
            "zucchini_retrieved": ("state", "zucchini.n.02_1", Inside, "electric_refrigerator.n.01_1", False),
            "fridge_closed": ("state", "electric_refrigerator.n.01_1", Open, False),
            "veggies_on_board_1": ("state", "bell_pepper.n.02_1", OnTop, "chopping_board.n.01", True),
            "veggies_on_board_2": ("state", "bell_pepper.n.02_2", OnTop, "chopping_board.n.01", True),
            "parer_picked_up": ("state", "parer.n.02_1", OnTop, "countertop.n.01_1", False),
            "peppers_diced": ("exists", "diced__bell_pepper.n.01_1", True),
            "beets_diced": ("exists", "diced__beet.n.01_1", True),
            "zucchini_diced": ("exists", "diced__zucchini.n.01_1", True),
        },
    ),
    "chopping_wood": lambda env: check_progress(
        env,
        {
            "robot_near_driveway": ("near", "agent.n.01_1", "driveway.n.01_1"),
            "robot_near_chopping_block": ("near", "agent.n.01_1", "chopping_block.n.01_1"),
            "axe_picked_up": ("state", "ax.n.01_1", OnTop, "driveway.n.01_1", False),
            "log_1_on_block": ("state", "log.n.01_1", OnTop, "chopping_block.n.01_1", True),
            "log_1_chopped": ("exists", "half__log.n.01_1", True),
            "log_1_chopped_2": ("exists", "half__log.n.01_2", True),
            "log_2_on_block": ("state", "log.n.01_2", OnTop, "chopping_block.n.01_1", True),
            "log_2_chopped": ("exists", "half__log.n.01_3", True),
            "log_2_chopped_2": ("exists", "half__log.n.01_4", True),
            "log_3_on_block": ("state", "log.n.01_3", OnTop, "chopping_block.n.01_1", True),
            "log_3_chopped": ("exists", "half__log.n.01_5", True),
            "log_3_chopped_2": ("exists", "half__log.n.01_6", True),
            "log_4_on_block": ("state", "log.n.01_4", OnTop, "chopping_block.n.01_1", True),
            "log_4_chopped": ("exists", "half__log.n.01_7", True),
            "log_4_chopped_2": ("exists", "half__log.n.01_8", True),
        },
    ),
    "cook_hot_dogs": lambda env: check_progress(
        env,
        {
            "robot_near_fridge": ("near", "agent.n.01_1", "electric_refrigerator.n.01_1"),
            "robot_near_microwave": ("near", "agent.n.01_1", "microwave.n.02_1"),
            "fridge_opened": ("state", "electric_refrigerator.n.01_1", Open, True),
            "hotdog_1_retrieved": ("state", "hotdog.n.02_1", Inside, "electric_refrigerator.n.01_1", False),
            "hotdog_2_retrieved": ("state", "hotdog.n.02_2", Inside, "electric_refrigerator.n.01_1", False),
            "fridge_closed": ("state", "electric_refrigerator.n.01_1", Open, False),
            "microwave_opened": ("state", "microwave.n.02_1", Open, True),
            "hotdog_1_in_microwave": ("state", "hotdog.n.02_1", Inside, "microwave.n.02_1", True),
            "hotdog_2_in_microwave": ("state", "hotdog.n.02_2", Inside, "microwave.n.02_1", True),
            "microwave_closed": ("state", "microwave.n.02_1", Open, False),
            "microwave_on": ("state", "microwave.n.02_1", ToggledOn, True),
            "hotdog_1_cooked": ("state", "hotdog.n.02_1", Cooked, True),
            "hotdog_2_cooked": ("state", "hotdog.n.02_2", Cooked, True),
        },
    ),
    "cook_bacon": lambda env: check_progress(
        env,
        {
            "robot_near_fridge": ("near", "agent.n.01_1", "electric_refrigerator.n.01_1"),
            "robot_near_stove": ("near", "agent.n.01_1", "stove.n.01_1"),
            "fridge_opened": ("state", "electric_refrigerator.n.01_1", Open, True),
            "tray_retrieved": ("state", "tray.n.01_1", Inside, "electric_refrigerator.n.01_1", False),
            "fridge_closed": ("state", "electric_refrigerator.n.01_1", Open, False),
            "bacon_in_pan": ("state", "bacon.n.01_1", Inside, "frying_pan.n.01_1", True),
            "pan_on_stove": ("state", "frying_pan.n.01_1", OnTop, "stove.n.01_1", True),
            "stove_on": ("state", "stove.n.01_1", ToggledOn, True),
            "bacon_1_cooked": ("state", "bacon.n.01_1", Cooked, True),
            "bacon_2_cooked": ("state", "bacon.n.01_2", Cooked, True),
            "bacon_3_cooked": ("state", "bacon.n.01_3", Cooked, True),
            "bacon_4_cooked": ("state", "bacon.n.01_4", Cooked, True),
            "bacon_5_cooked": ("state", "bacon.n.01_5", Cooked, True),
            "bacon_6_cooked": ("state", "bacon.n.01_6", Cooked, True),
        },
    ),
    "freeze_pies": lambda env: check_progress(
        env,
        {
            "robot_near_cabinet": ("near", "agent.n.01_1", "cabinet.n.01_1"),
            "robot_near_countertop": ("near", "agent.n.01_1", "countertop.n.01_1"),
            "robot_near_fridge": ("near", "agent.n.01_1", "electric_refrigerator.n.01_1"),
            "cabinet_opened": ("state", "cabinet.n.01_1", Open, True),
            "tupperware_1_retrieved": ("state", "tupperware.n.01_1", Inside, "cabinet.n.01_1", False),
            "tupperware_2_retrieved": ("state", "tupperware.n.01_2", Inside, "cabinet.n.01_1", False),
            "pie_1_picked_up": ("state", "apple_pie.n.01_1", OnTop, "plate.n.04_1", False),
            "pie_2_picked_up": ("state", "apple_pie.n.01_2", OnTop, "plate.n.04_2", False),
            "pie_1_in_tupperware": ("state", "apple_pie.n.01_1", Inside, "tupperware.n.01_1", True),
            "pie_2_in_tupperware": ("state", "apple_pie.n.01_2", Inside, "tupperware.n.01_2", True),
            "fridge_opened": ("state", "electric_refrigerator.n.01_1", Open, True),
            "tupperware_1_in_fridge": ("state", "tupperware.n.01_1", Inside, "electric_refrigerator.n.01_1", True),
            "tupperware_2_in_fridge": ("state", "tupperware.n.01_2", Inside, "electric_refrigerator.n.01_1", True),
            "fridge_closed": ("state", "electric_refrigerator.n.01_1", Open, False),
            "pie_1_frozen": ("state", "apple_pie.n.01_1", Frozen, True),
            "pie_2_frozen": ("state", "apple_pie.n.01_2", Frozen, True),
        },
    ),
    "canning_food": lambda env: check_progress(
        env,
        {
            "robot_near_fridge": ("near", "agent.n.01_1", "electric_refrigerator.n.01_1"),
            "robot_near_cabinet": ("near", "agent.n.01_1", "cabinet.n.01_1"),
            "robot_near_countertop": ("near", "agent.n.01_1", "countertop.n.01_1"),
            "fridge_opened": ("state", "electric_refrigerator.n.01_1", Open, True),
            "steak_retrieved": ("state", "steak.n.01_1", Inside, "electric_refrigerator.n.01_1", False),
            "pineapple_retrieved": ("state", "pineapple.n.02_1", Inside, "electric_refrigerator.n.01_1", False),
            "fridge_closed": ("state", "electric_refrigerator.n.01_1", Open, False),
            "cabinet_opened": ("state", "cabinet.n.01_1", Open, True),
            "bowls_retrieved": ("state", "bowl.n.01_1", Inside, "cabinet.n.01_1", False),
            "steak_on_board": ("state", "steak.n.01_1", OnTop, "chopping_board.n.01_1", True),
            "pineapple_on_board": ("state", "pineapple.n.02_1", OnTop, "chopping_board.n.01_1", True),
            "steak_diced": ("exists", "diced__steak.n.01_1", True),
            "pineapple_diced": ("exists", "diced__pineapple.n.01_1", True),
            "steak_in_bowl": ("state", "bowl.n.01_1", Filled, "diced__steak.n.01_1", True),
            "pineapple_in_bowl": ("state", "bowl.n.01_2", Filled, "diced__pineapple.n.01_1", True),
            "bowls_in_cabinet": ("state", "bowl.n.01_1", Inside, "cabinet.n.01_1", True),
            "cabinet_closed": ("state", "cabinet.n.01_1", Open, False),
        },
    ),
    "make_pizza": lambda env: check_progress(
        env,
        {
            "robot_near_countertop": ("near", "agent.n.01_1", "countertop.n.01_1"),
            "robot_near_fridge": ("near", "agent.n.01_1", "electric_refrigerator.n.01_1"),
            "robot_near_oven": ("near", "agent.n.01_1", "oven.n.01_1"),
            "onion_chopped": ("exists", "vidalia_onion.n.01_1", False),
            "fridge_opened": ("state", "electric_refrigerator.n.01_1", Open, True),
            "tupperware_1_retrieved": ("state", "tupperware.n.01_1", Inside, "electric_refrigerator.n.01_1", False),
            "tupperware_2_retrieved": ("state", "tupperware.n.01_2", Inside, "electric_refrigerator.n.01_1", False),
            "tupperware_3_retrieved": ("state", "tupperware.n.01_3", Inside, "electric_refrigerator.n.01_1", False),
            "pepperoni_1_in_bowl": ("state", "pepperoni.n.01_1", Inside, "bowl.n.01_1", True),
            "pepperoni_2_in_bowl": ("state", "pepperoni.n.01_2", Inside, "bowl.n.01_1", True),
            "pepperoni_3_in_bowl": ("state", "pepperoni.n.01_3", Inside, "bowl.n.01_1", True),
            "pepperoni_4_in_bowl": ("state", "pepperoni.n.01_4", Inside, "bowl.n.01_1", True),
            "mushroom_1_chopped": ("exists", "mushroom.n.05_1", False),
            "mushroom_2_chopped": ("exists", "mushroom.n.05_2", False),
            "pepperoni_1_on_dough": ("state", "pepperoni.n.01_1", OnTop, "pizza_dough.n.01_1", True),
            "pepperoni_2_on_dough": ("state", "pepperoni.n.01_2", OnTop, "pizza_dough.n.01_1", True),
            "pepperoni_3_on_dough": ("state", "pepperoni.n.01_3", OnTop, "pizza_dough.n.01_1", True),
            "pepperoni_4_on_dough": ("state", "pepperoni.n.01_4", OnTop, "pizza_dough.n.01_1", True),
            "cheese_on_pizza": ("state", "pizza_dough.n.01_1", Covered, "grated_cheese.n.01_1", True),
            "oven_opened": ("state", "oven.n.01_1", Open, True),
            "sheet_in_oven": ("state", "cookie_sheet.n.01_1", Inside, "oven.n.01_1", True),
            "oven_closed": ("state", "oven.n.01_1", Open, False),
            "oven_on": ("state", "oven.n.01_1", ToggledOn, True),
            "pizza_created": ("exists", "pizza.n.01_1", True),
            "pizza_on_sheet": ("state", "pizza.n.01_1", OnTop, "cookie_sheet.n.01_1", True),
        },
    ),
}
